In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import sklearn
warnings.simplefilter("ignore")

In [44]:
#import manajemen dataset
df=pd.read_excel("dataset_baru.xlsx", sheet_name =0)

In [45]:
df.describe()

,Kunjungan PerMinggu,Waktu Rata-Rata Situs(menit),Produk Dilihat,Beli Produk
count,200.000000,200.000000,200.000000,200.000000
mean,9.950000,29.600000,4.890000,0.060000
std,5.296012,16.923119,2.578983,0.238083
min,1.000000,2.000000,1.000000,0.000000
25%,6.000000,15.000000,3.000000,0.000000
50%,10.000000,27.000000,5.000000,0.000000
75%,14.000000,44.250000,7.000000,0.000000
max,19.000000,58.000000,9.000000,1.000000

In [46]:
start_col = 0
end_col = 3

x= df.iloc[:, start_col:end_col+1]
y=df.iloc[:,3]

In [47]:
y

0      0
1      0
2      0
3      0
4      0
      ..
195    0
196    0
197    1
198    0
199    0
Name: Beli Produk, Length: 200, dtype: int64

In [48]:
x

,Kunjungan PerMinggu,Waktu Rata-Rata Situs(menit),Produk Dilihat,Beli Produk
0,6,11,1,0
1,12,24,4,0
2,13,18,6,0
3,9,8,2,0
4,10,58,3,0
...,...,...,...,...
195,5,46,3,0
196,17,4,2,0
197,19,53,9,1
198,1,3,6,0
199,14,15,5,0

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=0, test_size=0.1)

In [50]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)

DecisionTreeClassifier()

In [51]:
import sklearn.metrics


y_predict = clf.predict(x_test)
akurasi = sklearn.metrics.accuracy_score(y_test, y_predict)

In [52]:
print (x_test)
print (akurasi)

     Kunjungan PerMinggu  Waktu Rata-Rata Situs(menit)  Produk Dilihat  \
18                    12                             3               1
170                    8                            16               4
107                   16                            29               1
98                     1                             3               6
177                    4                            37               1
182                    3                            14               6
5                     12                            25               5
146                   13                            51               9
12                     8                            31               9
152                    1                            56               2
61                     5                            50               1
125                    1                            33               7
180                    7                            22               6
154                   16                            26               4
80                     7                            22               6
7                     16                            29               1
33                     9                            49               1
130                    2                             3               3
37                     9                            18               4
74                     2                             8               4
183                   13                            28               3
145                   12                            50               3
45                    12                            50               3
159                    4                            20               7
60                     8                            26               1
123                   10                            11               4
179                   14                            57               8
185                    8                            50               7
122                    5                            35               5
44                    18                            14               1
16                     6                            52               5
55                     3                            22               2
150                   19                            11               1
111                   13                             2               3
22                     5                            35               5
189                   13                            15               8
129                    8                             7               4
4                     10                            58               3
83                    13                            28               3
106                    6                            11               4
134                   14                            55               4
66                     3                            44               8
26                    14                            42               8
113                   14                            42               4
168                   16                            14               4
63                     7                            14               7
8                      1                            21               7
75                    18                            54               9
118                   12                             3               1
143                    5                            38               8
71                    11                            25               5
124                   18                            55               4
184                   12                            50               6
97                    19                            53               9
149                   10                            21               5
24                    18                            55               4
30                     2                             3               3
160                    8                            26               1
40                     7                            55               8
56                     8                            40               7

     Beli Produk
18             0
170            0
107            0
98             0
177            0
182            0
5              0
146            1
12             0
152            0
61             0
125            0
180            0
154            0
80             0
7              0
33             0
130            0
37             0
74             0
183            0
145            0
45             0
159            0
60             0
123            0
179            1
185            0
122            0
44             0
16             0
55             0
150            0
111            0
22             0
189            0
129            0
4              0
83             0
106            0
134            0
66             0
26             0
113            0
168            0
63             0
8              0
75             1
118            0
143            0
71             0
124            1
184            0
97             1
149            0
24             1
30             0
160            0
40             0
56             0
1.0

In [53]:
#import management dataset untuk testing
df = pd.read_excel("dataset_baru.xlsx", sheet_name = 0)

In [54]:
df

,Kunjungan PerMinggu,Waktu Rata-Rata Situs(menit),Produk Dilihat,Beli Produk
0,6,11,1,0
1,12,24,4,0
2,13,18,6,0
3,9,8,2,0
4,10,58,3,0
...,...,...,...,...
195,5,46,3,0
196,17,4,2,0
197,19,53,9,1
198,1,3,6,0
199,14,15,5,0

In [55]:
x = df.iloc[:, start_col:end_col+1]
nama = df.iloc[:, 0]

In [56]:
x

,Kunjungan PerMinggu,Waktu Rata-Rata Situs(menit),Produk Dilihat,Beli Produk
0,6,11,1,0
1,12,24,4,0
2,13,18,6,0
3,9,8,2,0
4,10,58,3,0
...,...,...,...,...
195,5,46,3,0
196,17,4,2,0
197,19,53,9,1
198,1,3,6,0
199,14,15,5,0

In [57]:
nama

0       6
1      12
2      13
3       9
4      10
       ..
195     5
196    17
197    19
198     1
199    14
Name: Kunjungan PerMinggu, Length: 200, dtype: int64

In [58]:
y_predict = clf.predict(x)

In [59]:
nama=pd.DataFrame(nama)
nama=nama.reset_index(drop=True)
nama['ID']=nama.index+0
ey = pd.DataFrame(nama)

y_predict=pd.DataFrame(y_predict)
y_predict=y_predict.reset_index(drop=True)
y_predict['ID']=y_predict.index+0

ex = pd.DataFrame(y_predict)

In [60]:
ex.describe()

                0          ID
count  200.000000  200.000000
mean     0.060000   99.500000
std      0.238083   57.879185
min      0.000000    0.000000
25%      0.000000   49.750000
50%      0.000000   99.500000
75%      0.000000  149.250000
max      1.000000  199.000000

In [61]:
ey.describe()

       Kunjungan PerMinggu          ID
count           200.000000  200.000000
mean              9.950000   99.500000
std               5.296012   57.879185
min               1.000000    0.000000
25%               6.000000   49.750000
50%              10.000000   99.500000
75%              14.000000  149.250000
max              19.000000  199.000000

In [62]:
result = pd.merge(ex,ey, on='ID', how='inner')

In [63]:
result.to_excel('hasil_konsentrasi.xlsx', index=False)